version: '3.2'

services:
  postgres:
    container_name: 'postgres'
    image: 'timescale/timescaledb-ha:pg14-latest'
    environment:
      - POSTGRES_DB=energy_auth
      - POSTGRES_PASSWORD=Admin@1234
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
